/* Start tests/smoke_server.py first. Uses an isolated browser profile, fixture data only. */
const {chromium}=require('playwright');const assert=require('node:assert/strict');
const baseURL=process.env.SENTINEL_TEST_URL || 'http://127.0.0.1:8000';
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 try {
 const page=await browser.newPage({viewport:{width:1440,height:1100}});
 const errors=[];const external=[];
 page.on('pageerror',error=>errors.push(error.message));
 page.on('request',req=>{if(!req.url().startsWith(baseURL))external.push(req.url());});
 await page.goto(baseURL);
 await page.waitForFunction(()=>document.getElementById('cpu-pct').textContent==='25.0');
 assert.equal(await page.locator('#conn-label').textContent(),'Connected');
 assert.match(await page.locator('#insight-title').textContent(),/No sustained/);
 assert.match(await page.locator('#insight-leaders').textContent(),/CPU leaders/);
 assert.match(await page.locator('#disk-free').textContent(),/157.59 GB available/);
 assert.match(await page.locator('#disk-reclaimable').textContent(),/60.41 GB physically free.*97.18 GB reclaimable/);
 assert.equal(await page.locator('#disk-pct').textContent(),'84.2');
 assert.equal(await page.locator('#gpu-pct').textContent(),'23.0%');
 assert.match(await page.locator('#gpu-devices').textContent(),/shared RAM/);
 assert.match(await page.locator('#diagnostic-metrics').textContent(),/Normal.*Swap.*Disk read/);
 await page.fill('#watch-name','Example 134');
 await page.click('#watch-form button');
 await page.waitForFunction(()=>document.getElementById('watch-list').textContent.includes('running'));
 await page.click('#timeline-pause');
 const pausedMax=await page.evaluate(()=>correlatedChart.options.scales.x.max);
 await page.waitForTimeout(1200);
 assert.equal(await page.evaluate(()=>correlatedChart.options.scales.x.max),pausedMax);
 assert.equal(await page.locator('#timeline-pause').getAttribute('aria-pressed'),'true');
 await page.click('#timeline-pause');
 assert.ok(await page.evaluate(()=>correlatedChart.options.scales.x.max)>pausedMax);
 assert.equal(await page.evaluate(()=>watchChart.data.datasets.length),1);
 await page.click('#watch-list button');
 assert.equal(await page.evaluate(()=>watchChart.data.datasets.length),0);
 await page.click('[data-tab="settings"]');
 await page.locator('summary').filter({hasText:'Configure alerts'}).click();
 await page.waitForFunction(()=>!document.getElementById('alert-save').disabled);
 await page.fill('#alert-gpu-threshold','92');
 await page.fill('#alert-gpu-duration','30');
 await page.click('#alert-save');
 await page.waitForFunction(()=>document.getElementById('alert-status').textContent.includes('Saved'));
 assert.equal(await page.locator('#alert-gpu-threshold').inputValue(),'92');
 await page.locator('summary').filter({hasText:'Configure alerts'}).click();
 await page.selectOption('#sample-interval','2');
 await page.click('[data-tab="overview"]');
 await page.waitForTimeout(2100);
 assert.equal(await page.locator('#sample-interval').inputValue(),'2');
 await page.check('#compact');assert.equal(await page.locator('body').evaluate(el=>el.classList.contains('compact')),true);
 await page.uncheck('#compact');
 await page.screenshot({path:'/private/tmp/sentinel-overview.png',fullPage:true});
 await page.click('[data-tab="processes"]');
 assert.equal(await page.locator('#proc-body tr').count(),100);
 await page.click('#proc-next');assert.equal(await page.locator('#proc-body tr').count(),35);
 await page.fill('#proc-filter','Example 134');assert.equal(await page.locator('#proc-body tr').count(),1);
 await page.click('#proc-body button');assert.equal(await page.locator('#modal').isVisible(),true);
 await page.keyboard.press('Escape');assert.equal(await page.locator('#modal').isVisible(),false);
 await page.fill('#proc-filter','');await page.check('#proc-group');
 assert.equal(await page.locator('#proc-body button:not(:disabled)').count(),0);
 await page.click('[data-tab="system"]');
 await page.waitForSelector('#sys-body');await page.fill('#app-search','Editor');
 await page.waitForFunction(()=>document.getElementById('sys-body').textContent.includes('Example Editor'));
 assert.equal(await page.locator('#sys-body tbody tr').count(),1);
 await page.click('[data-tab="storage"]');
 await page.waitForFunction(()=>document.getElementById('dir-caption').textContent.includes('running'));
 await page.click('#storage-cancel');await page.waitForFunction(()=>document.getElementById('dir-caption').textContent.includes('cancelled'));
 await page.click('#storage-refresh');await page.waitForTimeout(2200);
 assert.match(await page.locator('#dir-list').textContent(),/inaccessible/);
 await page.click('#storage-cancel');
 await page.click('[data-tab="overview"]');
 await page.evaluate(()=>{globalThis.savedMessage=ws.onmessage;ws.onmessage=null;});
 await page.waitForTimeout(7500);
 assert.equal(await page.locator('#conn-label').textContent(),'Stale telemetry');
 await page.evaluate(()=>{ws.onmessage=globalThis.savedMessage;});
 await page.waitForFunction(()=>document.getElementById('conn-label').textContent==='Connected');
 const csv=page.waitForEvent('download');await page.click('#export-history');assert.equal((await csv).suggestedFilename(),'sentinel-history.csv');
 const json=page.waitForEvent('download');await page.click('#export-diagnostics');assert.equal((await json).suggestedFilename(),'sentinel-redacted.json');
 await page.click('#su-btn');await page.waitForFunction(()=>document.getElementById('su-status').textContent.includes('unknown'));
 await page.setViewportSize({width:390,height:844});
 await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 await page.waitForTimeout(250);
 const mobileShot=await page.screenshot({path:'/private/tmp/sentinel-mobile.png',fullPage:true});
 assert.equal(mobileShot.readUInt32BE(16),390,'Mobile screenshot must match viewport width');
 for(const tab of ['processes','system','overview']) {await page.click(`[data-tab="${tab}"]`);const width=await page.evaluate(()=>document.documentElement.scrollWidth);assert.ok(width<=392,`${tab} width ${width}`);}
 const dims=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));
 assert.ok(dims.scroll<=dims.width+2,JSON.stringify(dims));
 assert.deepEqual(external,[]);assert.deepEqual(errors,[]);
 console.log('PASS browser smoke: local assets, authenticated WS/API, telemetry, settings, process search/pagination/groups/modal, inventory search, progressive scan/cancel/partial warning, stale recovery, exports, unknown-update state, mobile width; no JS errors.');
 } finally { await browser.close(); }
})().catch(error=>{console.error(error);process.exit(1);});
