const {chromium}=require('playwright');const assert=require('node:assert/strict');
const base=process.env.SENTINEL_TEST_URL||'http://127.0.0.1:8001';
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 try {
  const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base);await page.waitForFunction(()=>lastSampleAt>0);
  await page.click('#investigate-peak');await page.waitForFunction(()=>document.getElementById('spike-detail').textContent.includes('CPU:'));
  assert.match(await page.locator('#spike-detail').textContent(),/Example/);
  await page.click('[data-tab="settings"]');
  await page.locator('#sessions-panel summary').click();
  await page.fill('#session-name','Before');await page.click('#session-save-form button');
  await page.waitForFunction(()=>savedA?.name==='Before');
  assert.equal(await page.evaluate(()=>savedA.includes_apps),false);
  await page.click('#session-peak');await page.waitForFunction(()=>document.getElementById('spike-detail').textContent.includes('excludes application'));
  const firstId=await page.locator('#session-a').inputValue();
  await page.fill('#session-name','After');await page.check('#session-apps');await page.click('#session-save-form button');
  await page.waitForFunction(()=>savedA?.name==='After');
  assert.equal(await page.evaluate(()=>savedA.includes_apps),true);
  await page.selectOption('#session-b',firstId);
  await page.waitForFunction(()=>sessionChart.data.datasets.length===2);
  assert.match(await page.locator('#session-comparison').textContent(),/sample mean/);
  await page.click('#session-peak');await page.waitForFunction(()=>document.getElementById('spike-detail').textContent.includes('Saved: After'));
  await page.check('#session-auto');await page.check('#session-apps');await page.click('#session-auto-save');
  await page.waitForFunction(()=>document.getElementById('session-status').textContent.includes('settings saved'));
  await page.reload();await page.waitForFunction(()=>!document.getElementById('session-auto-save').disabled);
  assert.equal(await page.locator('#session-auto').isChecked(),true);
  assert.equal(await page.locator('#session-apps').isChecked(),true);
  await page.click('[data-tab="settings"]');
  await page.locator('#sessions-panel summary').click();
  await page.uncheck('#session-auto');await page.click('#session-auto-save');
  await page.waitForFunction(()=>document.getElementById('session-status').textContent.includes('settings saved'));
  await page.selectOption('#session-a',firstId);await page.waitForFunction(()=>!document.getElementById('session-delete').disabled);
  page.once('dialog',dialog=>dialog.accept());await page.click('#session-delete');
  await page.waitForFunction(()=>document.getElementById('session-status').textContent.includes('deleted'));
  await page.click('[data-tab="settings"]');
  await page.check('#adaptive-sampling');
  await page.waitForFunction(()=>document.getElementById('adaptive-sampling').checked);
  await page.waitForTimeout(1200);assert.equal(await page.locator('#adaptive-sampling').isChecked(),true);
  await page.evaluate(()=>showSessionExpired());
  await page.click('#conn-pill');await page.waitForFunction(()=>!sessionDead && lastSampleAt>0);
  await page.click('[data-tab="settings"]');
  await page.locator('#sessions-panel summary').click();
  await page.setViewportSize({width:390,height:844});await page.waitForTimeout(300);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth)<=392,'expanded sessions must fit mobile');
  await page.screenshot({path:'/private/tmp/sentinel-milestones-mobile.png',fullPage:true});
  assert.deepEqual(errors,[]);
  console.log('PASS new milestones: historical apps, opt-in saves, comparison, persisted settings, deletion, adaptive controls, reconnect and mobile layout');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
